//Constants identifying actions.
export const EVENT_ACTIONS = {
    RESET_EVENT: 'RESET_EVENT',
    GET_EVENT : 'GET_EVENT',
    SET_CURRENT_EVENT : 'SET_CURRENT_EVENT',
    SET_CURRENT_EVENT_DATA : 'SET_CURRENT_EVENT_DATA',
    SET_CURRENT_EVENT_PARTICIPANTS : 'SET_CURRENT_EVENT_PARTICIPANTS',
    UPDATE_CURRENT_EVENT_PARTICIPANTS_USERS: 'UPDATE_CURRENT_EVENT_PARTICIPANTS_USERS',
    SET_CURRENT_EVENT_MODULES : 'SET_CURRENT_EVENT_MODULES',
    ATTEND_EVENT_SUCCESS: 'ATTEND_EVENT_SUCCESS',
    UNATTEND_EVENT_SUCCESS: 'UNATTEND_EVENT_SUCCESS',
    SET_EVENT_ADMIN_PRIVILEGES: 'SET_EVENT_ADMIN_PRIVILEGES',
    SET_EVENT_POLL: 'SET_EVENT_POLL',
    SET_EVENT_POLL_ANSWERS: 'SET_EVENT_POLL_ANSWERS',
    EVENT_POLL_ANSWERED: 'EVENT_POLL_ANSWERED',
    EVENT_POLL_REMOVED: 'EVENT_POLL_REMOVED',
    EVENT_POLL_ANSWERS_REMOVED: 'EVENT_POLL_ANSWERS_REMOVED'
};

export const EVENT_EDITOR_ACTIONS = {
    EVENT_DATA_UPDATED : 'EVENT_DATA_UPDATED',
    EVENT_MODULE_DATA_UPDATED : 'EVENT_MODULE_DATA_UPDATED',
    EVENT_POLL_EDITOR_OPEN: 'EVENT_POLL_EDITOR_OPEN',
    EVENT_POLL_EDITOR_CLOSE: 'EVENT_POLL_EDITOR_CLOSE',
    EVENT_POLL_EDITOR_RESET: 'EVENT_POLL_EDITOR_RESET',
    EVENT_POLL_CREATED: 'EVENT_POLL_CREATED'
};

export const USER_PROFILE_ACTIONS = {
    GET_ACCEPTED_EVENTS_DATA : 'GET_ACCEPTED_EVENTS_DATA',
    GET_ACCEPTED_EVENTS_MODULES : 'GET_ACCEPTED_EVENTS_MODULES',
    USER_PROFILE_UPDATED : 'USER_PROFILE_UPDATED',
    STANDARD_AVATARS_RECIEVED : 'STANDARD_AVATARS_RECIEVED',
    TOGGLE_AVATAR_SELECTOR : 'TOGGLE_AVATAR_SELECTOR',
    RESET_USER_PROFILE_DATA: 'RESET_USER_PROFILE_DATA',
    NO_EVENT_IN_LIST: 'NO_EVENT_IN_LIST'
};
