//Constants identifying actions.
export const EVENT_ACTIONS = {
    GET_EVENT : 'GET_EVENT',
    SET_CURRENT_EVENT : 'SET_CURRENT_EVENT',
    SET_CURRENT_EVENT_DATA : 'SET_CURRENT_EVENT_DATA',
    SET_CURRENT_EVENT_PARTICIPANTS : 'SET_CURRENT_EVENT_PARTICIPANTS',
    SET_CURRENT_EVENT_MODULES : 'SET_CURRENT_EVENT_MODULES',
    ATTEND_EVENT_SUCCESS: 'ATTEND_EVENT_SUCCESS',
    UNATTEND_EVENT_SUCCESS: 'UNATTEND_EVENT_SUCCESS'
};

export const EVENT_EDITOR_ACTIONS = {
    EDIT_DETAILS_TOGGLED : 'EDIT_DETAILS_TOGGLED',
    EDIT_DETAILS_TIME_TOGGLED : 'EDIT_DETAILS_TIME_TOGGLED',
    EDIT_DETAILS_LOC_TOGGLED: 'EDIT_DETAILS_LOC_TOGGLED',
    EDIT_DETAILS_MAP_TOGGLED: 'EDIT_DETAILS_MAP_TOGGLED'
};