//Constants identifying actions.
export const EVENT_ACTIONS = {
    GET_EVENT : 'GET_EVENT',
    SET_CURRENT_EVENT : 'SET_CURRENT_EVENT',
    ATTEND_EVENT_SUCCESS: 'ATTEND_EVENT_SUCCESS',
    UNATTEND_EVENT_SUCCESS: 'UNATTEND_EVENT_SUCCESS'
};